#+title: Figma Jam

* Зачем?
Чтобы проработать все вопросы связанные с архитектурой решения
- Разобраться в том как все устроено
- Проработать сомнительные требования и найти новые ограничения
- Добавить новые фичи или отказаться от тех которые не вписываются в текущий стейт
#+begin_quote
Если ты не можешь нарисовать процессы,
значит ты не знаешь как они работают
#+end_quote

* Что мы можем?
Визуализировать
- Домены
- Процессы
- Сущности
Через различные геометрические фигуры и эмодзи

* Давайте прототипировать проект
Допустим мы хотим создать систему обучения людей каким то навыкам
Наши основные фичи это
- Создание обучающего материала
- Выполнение заданий с привязкой к материалу
** Скрытые требования
- Система пользователей
  - С разными правами и статусами
- Система Заданий
  - Проверка
  - Оценка
** Ограничения
~Обычно они есть~, но нам повезло.
Сервис не должен быть быстрым, эффективным.
Непритязателен в инфраструктуре и прост в реализации
** Выбор технологий
- Docker/CI
- SQL DB
- General Purpose Language('s)
  - Auth lib
  - DB lib
  - UI kit
