#+TITLE: Введение в ClojureScript
#+AUTHOR: veschin

* Виды обучающего контента
- прикладной. взять инструмент, применить в работе
- абстрактный. рассмотреть топик, переформатировать мышление

обычно попытка обучить специалиста совершенно новой технологии разбивается о стену непонимания
- начинающий специалист часто открыт,
  но *не готов тратить ментальный ресурс* на развитие вне своего трека обучения,
  особенно когда область применения туманна
- практикующий специалист
  *обманывается иллюзией превосходства* собственного тулсета
  или пока слишком *любит процесс*, не замечая проблем,
  следовательно, не имея желания их решать
- состоявшийся специалист часто открыт к новым концепциям,
  но *предвзят к новым технологиям*, имеет негативный опыт взаимодействия с карго культом

архетипы пересекаются между собой в разных областях, все индивидуально, но вообщем картина примерно такая
* Верхушка айсберга
** Что такое карго культ
#+begin_quote
Во время второй мировой войны островитяне Меланезии видели как американцы строят взлётные полосы для снабжения войны на японском театре боевых действий. 
После ухода военных они строили самолеты из бамбука, наушники из какосов. Изображали сигналы посадки, находясь на построенной из дерева взлётно-посадочной полосе
#+end_quote
** Почему существуют другие языки программирования
у людей появляется потребность в решении определенных задач, над данными.

под конкретные задачи создается язык, который обрастает инфраструктурой, комьюнити, и основными направлениями разработки

каждый год развивается железо, программисты и бизнес, поэтому даже самые стабильные технологии устаревают и перестают удовлетворять потребности индустрии

*** Чем ограничивается язык
- синтаксис
- платформа рантайма
- производительность
- инфраструктура
- комьюнити

** Что такое фреймворк
любой язык общего назначения дает возможность разработать что угодно.
все ограничивается количеством времени которое нужно инвестировать в тулинг.

есть простые градации тулинга
- модуль. небольшой набор утилити функционала
- библиотека. набор утилити с идеями о том как обрабатывать данные
- фреймворк. набор утилити с
  - философией,
  - готовыми решениями о типовых проблемах, 
  - собственной инфраструктурой
- язык. набор утилити который включает все описанное выше и предлагает мажорные концепции отделяющие его от предшественников. он может быть
  - надстройкой над языком (расширение синтаксиса, например *Typescript*),
  - производным от языка (DSL - мини язык внутри языка, для определенных задач, например *JSX/TSX*)
  - языком паразитом. использовать рантайм существующего языка, например *ClojureScript/Dart/Elm*
** Что такое синтаксис
набор правил, по которому компилятор и программист определяют действия над данными
- идентификатор -  userName
- ключевое слово - if, function
- оператор - +, *, ===
- разделитель - (), {}, ;

фронтенд языка
- композиция правил

бэкенд языка
- парсер (выделяет из сплошного текста ключевые слова)  
- лексер (определяет что делать с ключевым словом)

** Что такое данные и структуры данных
данные - любой набор символов/цифр
вся наша работа - трансформация данных

базовые данные, как правило
- примитивы ~string number~
- структуры ~vector hashmap~ 

примеры того, как из базовых данных составляются сложные данные
- ~data = любая комбинация базовых данных~
- ~object = hashmap~
- ~identificator = резервируемый пользователем string + object ссылка на место в памяти~
- ~operator/keyword = резервируемый языком string~
- ~function = keyword ?identificator + vector/object + ?data~
*** Как бы выглядел JavaScript без синтаксиса, только из данных
#+begin_src js 
let x = 5;
[
    "let", // keyword,
    "=",   // operator
    "x",   // identificator,
    5      // data
] // => identificator

let d = function() { return 42 } →
[
    "let",             // keyword,
    "d",               // identificator,
    [
        "function",    // keyword,
        [],            // args vector,
        ["return", 42] // body
    ]                  
] // => identificator

d();
[
    d // identificator
] // => data

#+end_src
* Средний уровень айсберга
** Почему мутации это плохо

** Почему функций и данных достаточно
** Почему синтаксис не нужен
** Почему кодогенерация это хорошо
* Нижний уровень айсберга
** LISP
** Clojure
** ClojureScript
