#+title: Emacs Doom Воркшоп 1
#+author: veschin
#+language: ru

* Вступление
** Что такое Emacs
Это текстовый редактор,
который отличается высокой степенью настраиваемости и расширяемости.
Это популярный выбор для программистов и других пользователей,
которым нужен мощный и гибкий текстовый редактор.

** Зачем он нужен, когда есть VSCode, Sublime, IDEA ...
| Feature                               | Emacs | VS Code | IntelliJ IDEA |
|---------------------------------------+-------+---------+---------------|
| Стоимость                             | Free  | Free    | Paid          |
|                                       |       |         |               |
| Настраиваемость                       | High  | Medium  | Low           |
| Расширяемость                         | High  | Medium  | Low           |
| Поддерживаемые языки программирования | Many  | Many    | Many          |
| Функции и инструменты                 | Many  | Many    | Many          |
| Скорость работы                       | Fast  | Fast    | Medium/Slow   |
| Кривая обучения                       | Steep | Medium  | Medium        |
| Сообщество                            | Large | Large   | Large         |
| Популярность                          | High  | High    | High          |

** Фичи
-  Подстветка синтаксиса
-  Автокомплит
-  Отличный поиск
-  Расширения
*** Буфферы
Текст, который вы редактируете в Emacs, находится в объекте, называемом буфером.
Каждый раз, когда вы посещаете файл, буфер используется для хранения его текста.
- *Messages*
- *scratch*
*** Org
https://orgmode.org/features.html
Формат текста, состоящий из простых, но универсальных форм, которые представляют форматирование и структурную информацию.
*** Magit
https://magit.vc/
Полноценный текстовый пользовательский интерфейс для Git.
Он заполняет пробел между интерфейсом командной строки Git и различными графическими интерфейсами,
позволяя вам выполнять как тривиальные,
так и сложные задачи контроля версий с помощью всего лишь пары нажатий мнемонических клавиш.
*** LSP
https://github.com/emacs-lsp/lsp-mode
Language Server Protocol (LSP) - это открытый протокол на основе JSON-RPC для использования между редакторами исходного кода или интегрированными средами разработки (IDE) и серверами,
предоставляющими специфические для языка программирования функции,
такие как завершение кода, подсветка синтаксиса и маркировка предупреждений и ошибок,
а также процедуры рефакторинга.

Цель протокола - позволить реализовать и распространить поддержку языка программирования
~независимо от конкретного редактора или IDE~.
*** Finder
- Поиск по проекту
  ~SPC s p~
- Поиск файла
  ~SPC SPC~
- Поиск по буфферу
  ~SPC s s~
- Поиск конкретного файла
  ~SPC f f~
- Dired
  ~C-x d~

* Установка
** Зависимости [0/4]
- [ ] git
- [ ] emacs
- [ ] ripgrep
- [ ] fd
#+begin_src bash
brew install git emacs ripgrep fd
# or
sudo apt-get install git emacs ripgrep fd
#+end_src
** Doom
#+begin_src bash
git clone --depth 1 https://github.com/doomemacs/doomemacs ~/.config/emacs
~/.config/emacs/bin/doom install
#+end_src
** Настройка
*** EmacsLisp
Просто рандомные функции, чтобы вы не пугались, когда увидите
#+begin_src elisp
(defun my-function ()
  "This function prints 'Hello, world!'."
  (message "Hello, world!"))

(setq my-variable "Hello, world!")

(while (< my-counter 10)
  (message "The counter is %d." my-counter)
  (setq my-counter (+ my-counter 1)))

(if (> my-number 10)
    (message "The number is greater than 10.")
    (message "The number is less than or equal to 10."))

(defun print-date-and-time ()
  (message "The current date and time is: %s"
           (format-time-string "%Y-%m-%d %H:%M:%S")))
#+end_src
*** Где искать ответы
- Emacs Ru
  https://t.me/emacs_ru
- Clojure Ru / Emacs Thread
  https://t.me/clojure_ru/198186
- Quick Guide
  https://github.com/doomemacs/doomemacs/blob/master/docs/getting_started.org
  https://docs.doomemacs.org/latest/
- Мегамужик
  https://www.youtube.com/@DistroTube
- Reddit
  https://www.reddit.com/r/emacs/
*** Configs
В ~doom~ директории, лежит файл ~config.el~
В нем можно писать все свои настройки
#+begin_src emacs-lisp
(setq doom-font "Source Code Pro"
      doom-font-size 14
      doom-theme "doom-one")
#+end_src
*** Init
#+begin_src emacs-lisp
(doom! :input

       :completion
       company           ; the ultimate code completion backend
       (vertico +icons)           ; the search engine of the future

       :ui
       doom              ; what makes DOOM look the way it does
       doom-dashboard    ; a nifty splash screelln for Emacs
       (emoji +unicode)  ; 🙂
       hl-todo           ; highlight TODO/FIXME/NOTE/DEPRECATED/HACK/REVIEW
       ligatures         ; ligatures and symbols to make your code pretty again
       modeline          ; snazzy, Atom-inspired modeline, plus API
       nav-flash         ; blink cursor line after big motions
       (popup +defaults)   ; tame sudden yet inevitable temporary windows
       treemacs          ; a project drawer, like neotree but cooler
       unicode           ; extended unicode support for various languages
       vc-gutter         ; vcs diff in the fringe
       vi-tilde-fringe   ; fringe tildes to mark beyond EOB
       workspaces        ; tab emulation, persistence & separate workspaces
       zen               ; distraction-free coding or writing

       :editor
       (evil +everywhere); come to the dark side, we have cookies
       file-templates    ; auto-snippets for empty files
       fold              ; (nigh) universal code folding
       format  ; automated prettiness
       snippets          ; my elves. They type so I don't have to

       :emacs
       dired             ; making dired pretty [functional]
       electric          ; smarter, keyword-based electric-indent
       undo              ; persistent, smarter undo for your inevitable mistakes
       vc                ; version-control and Emacs, sitting in a tree

       :term

       :checkers

       :tools
       lookup              ; navigate your code and its documentation
       lsp               ; M-x vscode
       magit             ; a git porcelain for Emacs

       :os
       (:if IS-MAC macos)  ; improve compatibility with macOS

       :lang
       (clojure +lsp)      ; java with a lisp
       (go +lsp)         ; the hipster dialect
       (java +lsp)       ; the poster child for carpal tunnel syndrome
       (javascript +lsp)        ; all(hope(abandon(ye(who(enter(here))))))
       (yaml +lsp)              ; JSON, but readable
       (python +lsp)            ; beautiful is better than ugly
       emacs-lisp        ; drown in parentheses
       json              ; At least it ain't XML
       markdown          ; writing docs for people to ignore
       org               ; organize your plain life in plain text
       sh                ; she sells {ba,z,fi}sh shells on the C xor

       :email
       (mu4e +org +gmail)

       :app

       :config
       literate
       (default +bindings +smartparens))
#+end_src


* Использование
** Evil Mode
У Vim три основных мода:
- Normal mode режим по умолчанию. В нем можно использовать сочетания клавиш для перемещения по тексту и его редактирования.
- Insert mode используется для вставки текста в файл. Чтобы войти в режим, нажмите ~i~.
- Visual mode используется для выделения текста. Чтобы перейти в режим, нажмите ~v~.
*** Что использую я

| Key | Description                              |
|-----+------------------------------------------|
| v   | Запустить Visual mode                    |
| V   | Запустить Visual mode и выделите строку  |
| d   | Удалить текущий символ                   |
| dd  | Удалить строку                           |
| y   | Скопировать выделенный символ            |
| p   | Вставить перед курсором                  |
| P   | Вставить после курсора                   |
| gg  | Переместиться в начало файла             |
| G   | Переместиться в конец файла              |
| x   | Удалить символ под курсором              |
| r   | Заменить текущий символ другим символом  |
| i   | Вставить текст под курсором              |
| o   | Открыть новую строку под текущей строкой |
| O   | Открыть новую строку над текущей строкой |

** Demo
#+begin_src bash
du -h -d 1 ../repos
#+end_src

#+RESULTS:
| 97M  | ../repos/go         |
| 53M  | ../repos/python     |
| 11M  | ../repos/typescript |
| 161M | ../repos            |
