#+title: Emacs Doom Воркшоп 1
#+author: veschin
#+language: ru

* Вступление
** Что такое Emacs
Это текстовый редактор,
который отличается высокой степенью настраиваемости и расширяемости.
Это популярный выбор для программистов и других пользователей,
которым нужен мощный и гибкий текстовый редактор.

** Зачем он нужен, когда есть VSCode, Sublime, IDEA ...
| Feature                               | Emacs | VS Code | IntelliJ IDEA |
|---------------------------------------+-------+---------+---------------|
| Стоимость                             | Free  | Free    | Paid          |
|                                       |       |         |               |
| Настраиваемость                       | High  | Medium  | Low           |
| Расширяемость                         | High  | Medium  | Low           |
| Поддерживаемые языки программирования | Many  | Many    | Many          |
| Функции и инструменты                 | Many  | Many    | Many          |
| Скорость работы                       | Fast  | Fast    | Medium/Slow   |
| Кривая обучения                       | Steep | Medium  | Medium        |
| Сообщество                            | Large | Large   | Large         |
| Популярность                          | High  | High    | High          |

** Фичи
-  Подстветка синтаксиса
-  Автокомплит
-  Отличный поиск
-  Расширения
*** Буфферы
Текст, который вы редактируете в Emacs, находится в объекте, называемом буфером.
Каждый раз, когда вы посещаете файл, буфер используется для хранения его текста.
- *Messages*
- *scratch*
*** Org
https://orgmode.org/features.html
Формат текста, состоящий из простых, но универсальных форм, которые представляют форматирование и структурную информацию.
*** Magit
https://magit.vc/
Полноценный текстовый пользовательский интерфейс для Git.
Он заполняет пробел между интерфейсом командной строки Git и различными графическими интерфейсами,
позволяя вам выполнять как тривиальные,
так и сложные задачи контроля версий с помощью всего лишь пары нажатий мнемонических клавиш.
*** LSP
https://github.com/emacs-lsp/lsp-mode
Language Server Protocol (LSP) - это открытый протокол на основе JSON-RPC для использования между редакторами исходного кода или интегрированными средами разработки (IDE) и серверами,
предоставляющими специфические для языка программирования функции,
такие как завершение кода, подсветка синтаксиса и маркировка предупреждений и ошибок,
а также процедуры рефакторинга.

Цель протокола - позволить реализовать и распространить поддержку языка программирования
~независимо от конкретного редактора или IDE~.
*** Finder
- Поиск по проекту
  ~SPC s p~
- Поиск файла
  ~SPC SPC~
- Поиск по буфферу
  ~SPC s s~
- Поиск конкретного файла
  ~SPC f f~
- Dired
  ~C-x d~
*** Где искать ответы
- Emacs Ru
  https://t.me/emacs_ru
- Clojure Ru / Emacs Thread
  https://t.me/clojure_ru/198186
- Quick Guide
  https://github.com/doomemacs/doomemacs/blob/master/docs/getting_started.org
  https://docs.doomemacs.org/latest/
- Мегамужик
  https://www.youtube.com/@DistroTube
- Reddit
  https://www.reddit.com/r/emacs/

* Использование
** Evil Mode
У Vim три основных мода:
- Normal mode режим по умолчанию. В нем можно использовать сочетания клавиш для перемещения по тексту и его редактирования.
- Insert mode используется для вставки текста в файл. Чтобы войти в режим, нажмите ~i~.
- Visual mode используется для выделения текста. Чтобы перейти в режим, нажмите ~v~.
*** Что использую я

| Key | Description                              |
|-----+------------------------------------------|
| v   | Запустить Visual mode                    |
| V   | Запустить Visual mode и выделите строку  |
| d   | Удалить текущий символ                   |
| dd  | Удалить строку                           |
| y   | Скопировать выделенный символ            |
| p   | Вставить перед курсором                  |
| P   | Вставить после курсора                   |
| gg  | Переместиться в начало файла             |
| G   | Переместиться в конец файла              |
| x   | Удалить символ под курсором              |
| r   | Заменить текущий символ другим символом  |
| i   | Вставить текст под курсором              |
| o   | Открыть новую строку под текущей строкой |
| O   | Открыть новую строку над текущей строкой |

** Demo
#+begin_src bash
du -h -d 1 ../repos
#+end_src

#+RESULTS:
| 97M  | ../repos/go         |
| 53M  | ../repos/python     |
| 11M  | ../repos/typescript |
| 161M | ../repos            |
